#! /bin/sh
# /etc/init.d/brew_thermometer

# http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html

case "$1" in
  start)
    echo "Starting Brew Thermometer"
    node-dev /home/pi/Code/brew_thermometer/app.coffee
    ;; 
esac

exit 0
